name: deploy web

on: 
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      # - name: checkout repository
      #   uses: actions/checkout@v4

      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      # - name: install dependecies
      #   run: |
      #     npm install -g pnpm
      #     pnpm install 
      #     cd packages/db && pnpx prisma generate && cd ../..

      # - name: build the project
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: |
      #     pnpm run build

      - name: deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            source ~/.bashrc && cd ~/app-turbo-pnpm && git pull origin main && cd packages/db && pnpm prisma generate && cd ../.. && pnpm install && cd apps/web && pnpm run build && export DATABASE_URL=${{secrets.DATABASE_URL}} && pm2 restart turbo-app-fe --update-env || pm2 start "pnpm run start" --name=turbo-app-fe 




      